### ISSUE TITLE
Created Deck & Agendas

### ISSUE THREAD

**Issue by 5N00P1** [Salem2612/anrsealed#12]
In a created corp deck out of 3.0 (beta) I have the following Agendas:
- Government Takeover
- 2x Meteor Mining
This creates a deck, which has a very high number of agenda points, but also includes very hard to score agendas (5/2). So I can imagine some algorithm is needed for the agenda selection. To avoid that also some Jumons are added.

**Comment by Salem2612** [comment]
Thank's for your comment. This is a great idea to add a HARD_TO_SCORE tag to 9/6, 6/4, 5/2... Agenda cards and a constraint of "at most 1" per Sealed Deck. I add that feature on the todo list ^^

**Comment by Salem2612** [comment]
Add the HARD_TO_SCORE tag to the following agenda cards and limit the maximum of HARD_TO_SCORE cards to 1:
 - Mandatory Upgrades
 - Government Takeover
 - Vanity Project
 - Meteor Mining
 - Jumon

Fetal AI is not in the list, _continue to fear it_.

**Comment by 5N00P1** [comment]
agree to your solution!
