### ISSUE TITLE
TemuJ Contract

### ISSUE THREAD

**Issue by 5N00P1** [Salem2612/anrsealed#17]
Don't know why, but 6 out of 8 Decks have that cards at least once in their deck list.
This might be ok, but I was not sure, so fine if you just close this.

**Comment by Salem2612** [comment]
The algorithm mandatory picks ECO cards (cards to gain credits).
https://github.com/Salem2612/anrsealed/blob/master/www/json/v3.0.1/constraints.json
`      {"types":["ECO","COMMON"],"min":12,"max":99},`
TemuJjin Contract is an ECO card, that's why it is often picked.
