### ISSUE TITLE
Some ICE is very specific

### ISSUE THREAD

**Issue by 5N00P1** [Salem2612/anrsealed#18]
Have a deck with Oduduwa which does nothing in this deck.
If there would be something like ICE Wall or Space ICE I might see a reason. So perhaps a pairing is required?

**Comment by Salem2612** [comment]
I would say that Satellite Grid does nothing in Sealed, not Oduduwa. It's a 5 STR Code Gate with 2 End The Run subroutines for 7 credits. The specific effect about the advancement tokens is optional. The ICE does things even without this effect. I think Lotus Field also does things in Sealed format, even if its special effect is useless.

**Comment by 5N00P1** [comment]
agree
