### ISSUE TITLE
"Max 1 per deck" cards

### ISSUE THREAD

**Issue by MoiMagnus** [Salem2612/anrsealed#8]
I just had a set with "15 minutes" 3 times.
This card is "Max 1 per deck".
Probably not a good thing for this to be possible.

**Comment by Salem2612** [comment]
Hello and thank you for your report.
I managed to generate a set with 3x 15 Minutes when I select the cardpool sharing.
"3x 15 Minutes (Data and Destiny, NBN) [BROKEN] [CARD] [AGENDA]"

There is a bug somewhere. I'll fix it.

**Comment by MoiMagnus** [comment]
Yes, it was with cardpool sharing.

**Comment by Salem2612** [comment]
J'ai corrigé en ne mettant qu'un seul "15 Minutes" dans Data and Destiny au lieu de 3. Les 3 exemplaires ne servant en réalité à rien, même en Construit.

**Comment by MoiMagnus** [comment]
Mais du coup, avec collection partagée, ça risque d'empécher plusieurs joueurs d'avoir "15 Minutes", non ? (Après, c'est peut-être la seule solution.) Comment sont gérés les autres agendas uniques ?

**Comment by Salem2612** [comment]
Oui en l'état ça empêche plusieurs joueurs d'avoir cet agenda.

Le problème n'apparait qu'en mode Partage parce que dans ce mode, l'algorithme accepte qu'un joueur obtienne + d'exemplaires d'une carte que ce qui est préconisé normalement. Ceci dans le but de pouvoir partager plus facilement une collection en un plus grand nombre de joueurs. Pour une collection un peu réduite (quelques coresets et quelques deluxes), quand on limite trop le nombre d'exemplaires d'une carte par joueur, l'algorithme n'arrive pas à trouver assez de breakers ou de BROKEN par exemple.

15 Minutes est préconisé à 1 max par joueur en mode Une Collection Par Joueur, et à 3 max par joueur en mode Partage. D'où le bug que tu as trouvé. On a 4 solutions:
 1. Laisser la possibilité d'avoir jusqu'à 3 exemplaires de 15 Minutes pour un joueur. Ce qui laisse une chance aux autre joueurs d'en avoir. (v1.20.0)
 2. Limiter 15 Minutes à 1 seul exemplaire dans le pool de cartes. Les autres joueurs n'en auront pas. (v1.21.0)
 3. Ne pas faire de différences entre les modes Une Collection Par Joueur et Partage. Limiter à 1 exemplaire par joueur, mais 3 cartes dispo entre les joueurs. ça peut poser des problèmes pour partager une petite collection puisque ça va aussi limiter les autres BROKEN et les breakers.
 4. Ajouter une information pour chaque carte qui donne le maximum d'exemplaires par joueur, même en mode Partage. On y mettrait tous les agendas et cartes limités à 1 exemplaire par deck.

**Comment by MoiMagnus** [comment]
Solution 1 -> Non. Car si un joueur a 3 fois 15 minutes, soit on lui autorise à mettre les trois dans son deck et c'est complètement OP, soit on lui interdit et ça lui fait 2 slots BROKEN de "perdus".
Solution 2 -> C'est une solution acceptable, mais pas parfaite.
Solution 3 -> C'est la solution que je préfère personnellement, mais je peux voir que ça pose des problèmes aux personnes ayant une collection très restreinte. (L'utilisation que j'ai de anrsealed est de séparer ma collection (presque) complète en le maximum de paquets de scellés prêts à être utilisés, et d'utiliser ces paquets petit à petit)
Solution 4 -> Cette solution fait un bon compromis, mais c'est celle qui demande le plus de travail, pour un ajout raisonnablement mineur, donc c'est toi qui voit si tu souhaites passer du temps à l'implémenter.

Question à part : L'algorithme de selection est-il suffisament simple pour pouvoir être fait à la main ?
(Trier et séparer les cartes en tas, et à chaque fois que j'ai besoin d'un paquet de scellé, je prends aléatoirement un certain nombre de cartes de chaque tas, éventuellement en rejetant les doublons, et après le scellé, chaque joueur trie ses cartes et les remets dans les bons tas)
Ou est-ce que c'est plus subtil ?

**Comment by Salem2612** [comment]
La solution 2 étant pour le moment online je vais la laisser.
J'implémenterai la 4 quand j'aurais un peu de temps. Le plus gros du boulot se situe dans la base de données à mettre à jour. Vu que je suis à la bourre sur le cycle Kitara, ça sera l'occasion de l'ajouter ^^

L'algorithme se trouve dans le fichier suivant:
https://github.com/Salem2612/anrsealed/blob/master/www/json/v2.11.0/constraints.json
C'est une liste de contraintes à remplir pour chaque camp de chaque paquet de chaque joueur.
ça me parait compliqué à réaliser à l'identique en vrai avec des tas du fait que certaines cartes devraient se trouver dans plusieurs paquets à la fois. Par exemple dans le starter Runner, il faut commencer par piocher 12 cartes ECO-COMMON, puis piocher 3 breakers pompables de chaque type... puis à la fin il faut compléter pour avoir 70 COMMON. Mais ce complément peut être fait avec des ECO-COMMON ou des breakers pompables COMMON. Tu peux toujours compléter avec des COMMON pures, mais dans ce cas les joueurs n'auront pas le choix entre + de 3 breakers pompables par exemple.

**Comment by Salem2612** [comment]
The solution 4 has been added in v3.0.1.
