### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by MoiMagnus** [Salem2612/anrsealed#9]
1) "Freedom Through Equality" should be neutral (currently Shaper)

2) "K. P. Lynn" should be an upgrade (currently an Asset)

3) French "Sorted by Faction then Card Type" is messy due to the accents. For example : 

> HB / ASSET
1x Chaines de Montage Avancées
1x Secrétaire Agressive
1x Écraseur Cérébral

Strangely, in every other kind of sorting, "Écraseur Cérébral" is correctly sorted before "Secrétaire Agressive", "Sorted by Faction then Card Type" is the only bugged one.

**Comment by Salem2612** [comment]
Merci pour tes retours. Le tri n'était pas fait par rapport à la langue dans le paquet "Sorted by Faction then Card Type", du coup le "é" passait après le "s". Je corrige tout ça et je mets en ligne la version 2.11.0.

**Comment by Salem2612** [comment]
Voila la v2.11.0 est en ligne :) Merci pour ton aide.
